//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestnotification
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public bool IsAccepted { get; set; }
        public System.DateTime DateReceived { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public int RequestorID { get; set; }
        public bool IsDeclined { get; set; }
    
        public virtual request request { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
