//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestbid
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int RequestID { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> IsAwarded { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
    
        public virtual user user { get; set; }
        public virtual request request { get; set; }
    }
}
