//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public request()
        {
            this.requestbids = new HashSet<requestbid>();
            this.requestnotifications = new HashSet<requestnotification>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string CurrentLocation { get; set; }
        public int StatusID { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<requestbid> requestbids { get; set; }
        public virtual ICollection<requestnotification> requestnotifications { get; set; }
        public virtual user user { get; set; }
    }
}
