//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.requestbids = new HashSet<requestbid>();
            this.requestnotifications = new HashSet<requestnotification>();
            this.requestnotifications1 = new HashSet<requestnotification>();
            this.requests = new HashSet<request>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public bool IsActivated { get; set; }
        public string ImageUrl { get; set; }
        public int UserTypeID { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<requestbid> requestbids { get; set; }
        public virtual ICollection<requestnotification> requestnotifications { get; set; }
        public virtual ICollection<requestnotification> requestnotifications1 { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
